# Simple

# The default C compiler
CC = gcc

# The CFLAGS variable sets compile flags for gcc:
#  -g          compile with debug information
#  -Wall       give verbose compiler warnings
#  -O0         do not optimize generated code
#  -std=gnu99  use the GNU99 standard language definition
CFLAGS = -Wall -Wextra -Werror

newmastermind: mymastermind.c
	$(CC) $(CFLAGS) -o newmastermind mymastermind.c